/*
**	Command & Conquer Generals Zero Hour(tm)
**	Copyright 2025 Electronic Arts Inc.
**
**	This program is free software: you can redistribute it and/or modify
**	it under the terms of the GNU General Public License as published by
**	the Free Software Foundation, either version 3 of the License, or
**	(at your option) any later version.
**
**	This program is distributed in the hope that it will be useful,
**	but WITHOUT ANY WARRANTY; without even the implied warranty of
**	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**	GNU General Public License for more details.
**
**	You should have received a copy of the GNU General Public License
**	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// FILE: CommanderMenu.cpp /////////////////////////////////////////////////////////////////////////
// GeneralsX @feature ZH Commander 09/10/2026 The app's own settings, inside the game.
//
// Reached from the Options menu's ZH COMMANDER button (OptionsMenu.cpp). It shows the app
// version and offers what used to sit in the Android launcher: the simulation rate, the
// renderer, upscaling, interface and text size, the support report, the shell's remaining
// settings and a waiting update. Everything here is read when the game starts, so Apply saves
// and offers a restart. Settings in Options.ini are written by the engine itself; the ones the
// shell keeps (simulation rate, renderer) go through ZHCommander.h. A row whose platform does
// not have the setting is hidden. Layout: Window/Menus/CommanderMenu.wnd, generated by
// scripts/tooling/wnd/make-commander-menu.py.
///////////////////////////////////////////////////////////////////////////////////////////////////

#include "PreRTS.h"

#include "Common/NameKeyGenerator.h"
#include "Common/OptionPreferences.h"
#include "Common/ZHCommander.h"
#include "GameClient/Gadget.h"
#include "GameClient/GadgetPushButton.h"
#include "GameClient/GadgetStaticText.h"
#include "GameClient/GameWindow.h"
#include "GameClient/GameWindowManager.h"
#include "GameClient/GUICallbacks.h"
#include "GameClient/KeyDefs.h"
#include "GameClient/MessageBox.h"
#include "GameClient/Shell.h"
#include "GameClient/WindowLayout.h"

namespace
{
	struct Choice
	{
		const char *value;
		const wchar_t *label;
	};

	const Choice SIM_HZ[] = {
		{ "30", L"30 HZ" },
		{ "60", L"60 HZ (PLAY WITH PC)" },
	};
	const Choice RENDERERS[] = {
		{ "gles", L"OPENGL ES" },
		{ "gles_angle", L"OPENGL ES (ANGLE)" },
		{ "vulkan", L"VULKAN" },
	};
	// FSR 1's modes and scales, as SetupActivity offered them (GXUpscale in Options.ini).
	const Choice UPSCALE[] = {
		{ "off", L"OFF" },
		{ "ultra", L"ULTRA QUALITY (77%)" },
		{ "quality", L"QUALITY (67%)" },
		{ "balanced", L"BALANCED (59%)" },
		{ "performance", L"PERFORMANCE (50%)" },
	};
	const Int UI_SCALE_MIN = 100, UI_SCALE_MAX = 200, UI_SCALE_STEP = 10;
	// -1 is "the game's own size" (ResolutionFontAdjustment absent).
	const Int TEXT_SIZE_MIN = 50, TEXT_SIZE_MAX = 150, TEXT_SIZE_STEP = 10;

	// One row: a value that a button steps through, the value it had on entry, and its widgets.
	struct Row
	{
		const char *name;
		GameWindow *label;
		GameWindow *button;
		Int value;
		Int initial;
	};

	enum { ROW_SIM_HZ, ROW_RENDERER, ROW_UPSCALE, ROW_UI_SCALE, ROW_TEXT_SIZE, ROW_TELEMETRY, ROW_COUNT };

	Row s_rows[ROW_COUNT] = {
		{ "SimHz" }, { "Renderer" }, { "Upscale" }, { "UiScale" }, { "TextSize" }, { "Telemetry" },
	};

	GameWindow *s_buttonReport = nullptr;
	GameWindow *s_buttonMore = nullptr;
	GameWindow *s_buttonUpdate = nullptr;
	GameWindow *s_buttonMods = nullptr;
	GameWindow *s_buttonAccept = nullptr;
	GameWindow *s_buttonBack = nullptr;

	GameWindow *find(const char *name)
	{
		AsciiString full;
		full.format("CommanderMenu.wnd:%s", name);
		return TheWindowManager->winGetWindowFromId(nullptr, TheNameKeyGenerator->nameToKey(full));
	}

	void setLabel(GameWindow *window, const wchar_t *text)
	{
		if (window != nullptr)
			GadgetStaticTextSetText(window, UnicodeString(text));
	}

	template <size_t N>
	Int countOf(const Choice (&)[N])
	{
		return (Int)N;
	}

	template <size_t N>
	Int indexOf(const Choice (&choices)[N], const char *value)
	{
		for (size_t i = 0; i < N; ++i)
			if (strcmp(choices[i].value, value) == 0)
				return (Int)i;
		return 0;
	}

	void showRowValue(Int row)
	{
		Row &r = s_rows[row];
		if (r.button == nullptr)
			return;
		UnicodeString text;
		switch (row)
		{
			case ROW_SIM_HZ: text = SIM_HZ[r.value].label; break;
			case ROW_RENDERER: text = RENDERERS[r.value].label; break;
			case ROW_UPSCALE: text = UPSCALE[r.value].label; break;
			case ROW_UI_SCALE: text.format(L"%d%%", r.value); break;
			case ROW_TEXT_SIZE:
				if (r.value < 0)
					text = L"GAME DEFAULT";
				else
					text.format(L"%d%%", r.value);
				break;
			case ROW_TELEMETRY: text = r.value ? L"ON" : L"OFF"; break;
		}
		GadgetButtonSetText(r.button, text);
	}

	void stepRow(Int row)
	{
		Row &r = s_rows[row];
		switch (row)
		{
			case ROW_SIM_HZ: r.value = (r.value + 1) % countOf(SIM_HZ); break;
			case ROW_RENDERER: r.value = (r.value + 1) % countOf(RENDERERS); break;
			case ROW_UPSCALE: r.value = (r.value + 1) % countOf(UPSCALE); break;
			case ROW_UI_SCALE:
				r.value = r.value >= UI_SCALE_MAX ? UI_SCALE_MIN : r.value + UI_SCALE_STEP;
				break;
			case ROW_TEXT_SIZE:
				if (r.value < 0)
					r.value = TEXT_SIZE_MIN;
				else
					r.value = r.value >= TEXT_SIZE_MAX ? -1 : r.value + TEXT_SIZE_STEP;
				break;
			case ROW_TELEMETRY:
				// Takes effect at once and needs no restart, so it is not one of Apply's changes.
				r.value = !r.value;
				r.initial = r.value;
				ZHCommander::hooks().setSetting("telemetry", r.value ? "on" : "off");
				break;
		}
		showRowValue(row);
	}

	void hideRow(Int row)
	{
		if (s_rows[row].label)
			s_rows[row].label->winHide(TRUE);
		if (s_rows[row].button)
			s_rows[row].button->winHide(TRUE);
		s_rows[row].button = nullptr;
	}

	Bool anyChanged()
	{
		for (Int i = 0; i < ROW_COUNT; ++i)
			if (s_rows[i].button != nullptr && s_rows[i].value != s_rows[i].initial)
				return TRUE;
		return FALSE;
	}

	void save()
	{
		ZHCommander::Hooks &h = ZHCommander::hooks();
		const Row &simHz = s_rows[ROW_SIM_HZ];
		if (simHz.button != nullptr && simHz.value != simHz.initial)
			h.setSetting("sim_hz", SIM_HZ[simHz.value].value);
		const Row &renderer = s_rows[ROW_RENDERER];
		if (renderer.button != nullptr && renderer.value != renderer.initial)
			h.setSetting("render_backend", RENDERERS[renderer.value].value);

		OptionPreferences pref;
		const Row &upscale = s_rows[ROW_UPSCALE];
		if (upscale.button != nullptr)
		{
			pref["GXUpscale"] = UPSCALE[upscale.value].value;
			pref.erase(AsciiString("GXUpscaler"));  // an earlier launcher's key; GXUpscale replaces it
		}
		const Row &uiScale = s_rows[ROW_UI_SCALE];
		if (uiScale.button != nullptr)
			pref.setInt("GXUiScale", uiScale.value);
		const Row &textSize = s_rows[ROW_TEXT_SIZE];
		if (textSize.button != nullptr)
		{
			if (textSize.value < 0)
				pref.erase(AsciiString("ResolutionFontAdjustment"));
			else
				pref.setInt("ResolutionFontAdjustment", textSize.value);
		}
		pref.write();
	}

	void restartNow()
	{
		ZHCommander::hooks().restart();
	}

	void leave()
	{
		TheShell->pop();
	}

	// The ONLINE row: who this device is signed in as, and SIGN IN or SIGN OUT. Refreshed while the
	// screen is open, since the sign-in finishes in the browser and comes back here.
	GameWindow *s_labelOnline = nullptr;
	GameWindow *s_buttonOnline = nullptr;
	Bool s_signedIn = FALSE;
	Int s_onlinePollFrames = 0;

	void refreshOnline()
	{
		ZHCommander::Hooks &h = ZHCommander::hooks();
		if (s_labelOnline == nullptr || s_buttonOnline == nullptr || h.onlineAccount == nullptr)
			return;
		char name[64];
		s_signedIn = h.onlineAccount(name, sizeof(name));
		UnicodeString text;
		if (s_signedIn)
			text.format(L"Signed in as %hs", name);
		else
			text = L"Not signed in";
		GadgetStaticTextSetText(s_labelOnline, text);
		GadgetButtonSetText(s_buttonOnline, UnicodeString(s_signedIn ? L"SIGN OUT" : L"SIGN IN"));
	}

	// MODS, with how many packs are on ("MODS: 2 OF 5 ON"); hidden where the platform has none.
	void refreshMods()
	{
		ZHCommander::Hooks &h = ZHCommander::hooks();
		if (s_buttonMods == nullptr)
			return;
		if (h.openMods == nullptr)
		{
			s_buttonMods->winHide(TRUE);
			return;
		}
		char summary[48];
		UnicodeString text;
		if (h.modsSummary != nullptr && h.modsSummary(summary, sizeof(summary)))
		{
			for (char *c = summary; *c; ++c)
				*c = (char)toupper((unsigned char)*c);
			text.format(L"MODS: %hs", summary);
		}
		else
			text = L"MODS";
		GadgetButtonSetText(s_buttonMods, text);
	}

	void signOutNow()
	{
		if (ZHCommander::hooks().onlineSignOut)
			ZHCommander::hooks().onlineSignOut();
		refreshOnline();
		refreshMods();
	}
}

//-------------------------------------------------------------------------------------------------
void CommanderMenuInit(WindowLayout *layout, void *userData)
{
	ZHCommander::Hooks &h = ZHCommander::hooks();
	for (Int i = 0; i < ROW_COUNT; ++i)
	{
		AsciiString name;
		name.format("Label%s", s_rows[i].name);
		s_rows[i].label = find(name.str());
		name.format("Button%s", s_rows[i].name);
		s_rows[i].button = find(name.str());
	}
	s_buttonReport = find("ButtonReport");
	s_buttonMore = find("ButtonMore");
	s_buttonUpdate = find("ButtonUpdate");
	s_buttonMods = find("ButtonMods");
	s_buttonAccept = find("ButtonAccept");
	s_buttonBack = find("ButtonBack");

	setLabel(find("LabelTitle"), L"ZH COMMANDER");
	UnicodeString version;
	version.format(L"Version %hs", ZHCommander::appVersion() ? ZHCommander::appVersion() : "?");
	if (find("LabelVersion"))
		GadgetStaticTextSetText(find("LabelVersion"), version);
	setLabel(s_rows[ROW_SIM_HZ].label, L"Game speed (simulation rate)");
	setLabel(s_rows[ROW_RENDERER].label, L"Renderer");
	setLabel(s_rows[ROW_UPSCALE].label, L"Upscaling (OpenGL ES)");
	setLabel(s_rows[ROW_UI_SCALE].label, L"Interface size");
	setLabel(s_rows[ROW_TEXT_SIZE].label, L"Text size");
	setLabel(s_rows[ROW_TELEMETRY].label, L"Usage data (anonymous)");
	setLabel(find("LabelSectionGame"), L"GAME");
	setLabel(find("LabelSectionOnline"), L"ONLINE");
	setLabel(find("LabelSupport"), L"SUPPORT AND APP");
	s_labelOnline = find("LabelOnline");
	s_buttonOnline = find("ButtonOnline");
	if (h.onlineAccount == nullptr)
	{
		// No GeneralsOnline on this platform: the whole section goes.
		if (find("LabelSectionOnline"))
			find("LabelSectionOnline")->winHide(TRUE);
		if (s_labelOnline)
			s_labelOnline->winHide(TRUE);
		if (s_buttonOnline)
			s_buttonOnline->winHide(TRUE);
		s_buttonOnline = nullptr;
	}
	s_onlinePollFrames = 0;
	refreshOnline();
	refreshMods();
	setLabel(find("LabelStatus"), L"Changes take effect when the game starts again.");

	// Values on entry, from the same places the game reads them at startup.
	char value[32];
	if (h.getSetting != nullptr && h.setSetting != nullptr)
	{
		s_rows[ROW_SIM_HZ].value = h.getSetting("sim_hz", value, sizeof(value)) ? indexOf(SIM_HZ, value) : 0;
		s_rows[ROW_RENDERER].value = h.getSetting("render_backend", value, sizeof(value)) ? indexOf(RENDERERS, value) : 0;
		s_rows[ROW_TELEMETRY].value = h.getSetting("telemetry", value, sizeof(value)) && strcmp(value, "off") != 0;
	}
	else
	{
		hideRow(ROW_SIM_HZ);
		hideRow(ROW_RENDERER);
		hideRow(ROW_TELEMETRY);
		// Upscaling is done by the OpenGL ES backend, which only the Android build has.
		hideRow(ROW_UPSCALE);
	}
	OptionPreferences pref;
	s_rows[ROW_UPSCALE].value = indexOf(UPSCALE, pref.getAsciiString("GXUpscale", "off").str());
	const Int uiScale = pref.getInt("GXUiScale", UI_SCALE_MIN);
	s_rows[ROW_UI_SCALE].value = max(UI_SCALE_MIN, min(UI_SCALE_MAX, uiScale - uiScale % UI_SCALE_STEP));
	const Int textSize = pref.getInt("ResolutionFontAdjustment", -1);
	s_rows[ROW_TEXT_SIZE].value = textSize < 0 ? -1
		: max(TEXT_SIZE_MIN, min(TEXT_SIZE_MAX, textSize - textSize % TEXT_SIZE_STEP));
	for (Int i = 0; i < ROW_COUNT; ++i)
	{
		s_rows[i].initial = s_rows[i].value;
		showRowValue(i);
	}

	if (s_buttonReport)
	{
		GadgetButtonSetText(s_buttonReport, UnicodeString(L"SEND A REPORT"));
		s_buttonReport->winHide(h.shareSupportReport == nullptr);
	}
	if (s_buttonMore)
	{
		GadgetButtonSetText(s_buttonMore, UnicodeString(L"ADVANCED"));
		s_buttonMore->winHide(h.openMoreSettings == nullptr);
	}
	if (s_buttonUpdate)
	{
		char offer[32];
		bool mandatory = false;
		UnicodeString text;
		if (h.appUpdateOffer != nullptr && h.appUpdateOffer(offer, sizeof(offer), &mandatory))
		{
			text.format(L"INSTALL %hs", offer);
			s_buttonUpdate->winEnable(TRUE);
		}
		else
		{
			text = L"UP TO DATE";
			s_buttonUpdate->winEnable(FALSE);
		}
		GadgetButtonSetText(s_buttonUpdate, text);
		s_buttonUpdate->winHide(h.appUpdateOffer == nullptr);
	}
	if (s_buttonAccept)
		GadgetButtonSetText(s_buttonAccept, UnicodeString(L"APPLY"));
	if (s_buttonBack)
		GadgetButtonSetText(s_buttonBack, UnicodeString(L"BACK"));

	layout->hide(FALSE);
	TheWindowManager->winSetFocus(find("CommanderMenuParent"));
}

//-------------------------------------------------------------------------------------------------
void CommanderMenuUpdate(WindowLayout *layout, void *userData)
{
	if (++s_onlinePollFrames >= 30)
	{
		s_onlinePollFrames = 0;
		refreshOnline();
		refreshMods();
	}
}

//-------------------------------------------------------------------------------------------------
void CommanderMenuShutdown(WindowLayout *layout, void *userData)
{
	for (Int i = 0; i < ROW_COUNT; ++i)
	{
		s_rows[i].label = nullptr;
		s_rows[i].button = nullptr;
	}
	s_buttonReport = s_buttonMore = s_buttonUpdate = s_buttonMods = s_buttonAccept = s_buttonBack = nullptr;
	s_labelOnline = s_buttonOnline = nullptr;

	layout->hide(TRUE);
	TheShell->shutdownComplete(layout);
}

//-------------------------------------------------------------------------------------------------
WindowMsgHandledType CommanderMenuSystem(GameWindow *window, UnsignedInt msg,
	WindowMsgData mData1, WindowMsgData mData2)
{
	switch (msg)
	{
		case GWM_INPUT_FOCUS:
		{
			if (mData1 == TRUE)
				*(Bool *)mData2 = TRUE;
			return MSG_HANDLED;
		}

		case GBM_SELECTED:
		{
			GameWindow *control = (GameWindow *)mData1;
			ZHCommander::Hooks &h = ZHCommander::hooks();
			for (Int i = 0; i < ROW_COUNT; ++i)
			{
				if (control != nullptr && control == s_rows[i].button)
				{
					stepRow(i);
					return MSG_HANDLED;
				}
			}
			if (control == s_buttonReport && h.shareSupportReport)
				h.shareSupportReport();
			else if (control == s_buttonOnline && s_buttonOnline != nullptr)
			{
				if (!s_signedIn && h.onlineSignIn)
					h.onlineSignIn();
				else if (s_signedIn)
					MessageBoxYesNo(UnicodeString(L"GENERALSONLINE"),
						UnicodeString(L"Sign out of GeneralsOnline on this device?"), signOutNow, nullptr);
			}
			else if (control == s_buttonMore && h.openMoreSettings)
				h.openMoreSettings();
			else if (control == s_buttonMods && s_buttonMods != nullptr && h.openMods)
				h.openMods();
			else if (control == s_buttonUpdate && h.startAppUpdate)
				h.startAppUpdate();
			else if (control == s_buttonBack)
				leave();
			else if (control == s_buttonAccept)
			{
				if (!anyChanged())
				{
					leave();
					break;
				}
				save();
				if (h.restart != nullptr)
					MessageBoxYesNo(UnicodeString(L"ZH COMMANDER"),
						UnicodeString(L"Saved. Restart the game now to use the new settings?"),
						restartNow, leave);
				else
					MessageBoxOk(UnicodeString(L"ZH COMMANDER"),
						UnicodeString(L"Saved. Close the game and open it again to use the new settings."),
						leave);
			}
			return MSG_HANDLED;
		}

		default:
			break;
	}
	return MSG_IGNORED;
}

//-------------------------------------------------------------------------------------------------
WindowMsgHandledType CommanderMenuInput(GameWindow *window, UnsignedInt msg,
	WindowMsgData mData1, WindowMsgData mData2)
{
	if (msg == GWM_CHAR && (UnsignedByte)mData1 == KEY_ESC)
	{
		if (BitIsSet(mData2, KEY_STATE_UP))
			leave();
		return MSG_HANDLED;
	}
	return MSG_IGNORED;
}
